# ---- begin snakebids boilerplate ----------------------------------------------

from glob import glob
import snakebids
from snakebids import bids


configfile: "config/snakebids.yml"


# writes inputs_config.yml and updates config dict
config.update(
    snakebids.generate_inputs(
        bids_dir=config["bids_dir"],
        pybids_inputs=config["pybids_inputs"],
        derivatives=config["derivatives"],
        participant_label=config["participant_label"],
        exclude_participant_label=config["exclude_participant_label"],
    )
)


# this adds constraints to the bids naming
wildcard_constraints:
    **snakebids.get_wildcard_constraints(config["pybids_inputs"]),


# ---- end snakebids boilerplate ------------------------------------------------

model = config["use_downloaded"]


include: "rules/common.smk"



rule all_test:
    input:
        nii=expand(
            bids(
                root="results",
                datatype="func",
                desc="brain",
                suffix="mask.nii.gz",
                **config["input_wildcards"]["bold"]
            ),
            zip,
            **config["input_zip_lists"]["bold"]
        ),

include: "rules/inference.smk"


